import { motion } from "framer-motion";
import NavHeader from "@/components/dashboard/NavHeader";
import { Cpu, BarChart3, FlaskConical, Network } from "lucide-react";

const fade = (delay = 0) => ({ initial: { opacity: 0, y: 16 }, animate: { opacity: 1, y: 0 }, transition: { delay, duration: 0.5 } });

const Section = ({ title, icon: Icon, children, delay = 0 }: { title: string; icon: React.ElementType; children: React.ReactNode; delay?: number }) => (
  <motion.section {...fade(delay)} className="bg-card border border-border rounded-lg p-6 md:p-8 space-y-4">
    <div className="flex items-center gap-3 mb-2">
      <Icon className="w-5 h-5 text-foreground" />
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
    </div>
    {children}
  </motion.section>
);

const simParams = [
  { param: "Simulator", value: "NS-3" },
  { param: "Number of Nodes", value: "20" },
  { param: "Area", value: "200 × 200 m" },
  { param: "Initial Energy", value: "0.5 J per node" },
  { param: "Cluster Head Percentage", value: "15–20%" },
  { param: "Communication Radius", value: "50 m" },
  { param: "Rounds", value: "200" },
];

const algorithms = [
  { name: "LEACH", desc: "Random probabilistic cluster head election based on threshold." },
  { name: "CHEF", desc: "Fuzzy logic-based cluster head election using energy and distance." },
  { name: "HEED", desc: "Hybrid energy-efficient distributed clustering using residual energy." },
  { name: "DEEC", desc: "Distributed energy-efficient clustering for heterogeneous networks." },
  { name: "K-Means", desc: "Centroid-based clustering with distance-optimized assignments." },
  { name: "Custom MCDM/WSM", desc: "Multi-criteria decision-making using Weighted Sum Method with energy, distance, and neighbor count." },
];

const Methodology = () => (
  <div className="min-h-screen bg-background">
    <NavHeader />
    <div className="max-w-4xl mx-auto px-6 py-10 space-y-8">
      <motion.div {...fade(0)} className="text-center space-y-3">
        <h1 className="text-2xl md:text-3xl font-bold text-foreground">Methodology</h1>
        <p className="text-sm text-muted-foreground max-w-2xl mx-auto leading-relaxed">
          Simulation setup, clustering algorithms, consensus design, and encryption implementation.
        </p>
      </motion.div>

      {/* Simulation Setup */}
      <Section title="Simulation Setup" icon={Cpu} delay={0.1}>
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          Simulations were conducted using NS-3 with 20 IoT nodes deployed in a 200×200 meter area. Each node begins with 0.5 J of energy and operates over 200 rounds.
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left py-2 text-foreground font-medium">Parameter</th>
                <th className="text-left py-2 text-foreground font-medium">Value</th>
              </tr>
            </thead>
            <tbody>
              {simParams.map((row, i) => (
                <tr key={i} className="border-b border-border/50">
                  <td className="py-2 text-muted-foreground">{row.param}</td>
                  <td className="py-2 font-mono text-foreground text-xs">{row.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* Clustering Algorithms */}
      <Section title="Clustering Algorithm Comparison" icon={Network} delay={0.15}>
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          Six clustering algorithms were implemented and compared for energy efficiency, fairness, and network lifetime.
        </p>
        <div className="grid gap-3">
          {algorithms.map((alg, i) => (
            <div key={i} className="flex gap-3 items-start">
              <span className="font-mono text-xs text-foreground bg-secondary px-2 py-1 rounded shrink-0 mt-0.5">{alg.name}</span>
              <span className="text-sm text-muted-foreground leading-relaxed">{alg.desc}</span>
            </div>
          ))}
        </div>
      </Section>

      {/* Consensus */}
      <Section title="Extended DPoL Consensus" icon={FlaskConical} delay={0.2}>
        <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
          <p>The Extended Delegated Proof-of-Luck (DPoL) consensus protocol selects a block proposer based on randomized luck values generated by cluster heads.</p>
          <ol className="list-decimal pl-5 space-y-1.5">
            <li>Each cluster head generates a random luck value between 0 and 1.</li>
            <li>The median of all values is calculated.</li>
            <li>The cluster head closest to the median is selected as the block proposer.</li>
            <li>The top log(n) cluster heads serve as delegates.</li>
            <li>Delegates vote to approve or reject the proposed block.</li>
            <li>Consensus is achieved when a majority approves.</li>
          </ol>
        </div>
      </Section>

      {/* Encryption */}
      <Section title="Post-Quantum Encryption" icon={BarChart3} delay={0.25}>
        <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
          <p>The encryption pipeline uses a hybrid approach combining lattice-based key encapsulation with symmetric encryption:</p>
          <ol className="list-decimal pl-5 space-y-1.5">
            <li><span className="text-foreground font-medium">Kyber-512 (ML-KEM)</span> — Generates a quantum-resistant shared secret through key encapsulation.</li>
            <li><span className="text-foreground font-medium">AES-256 Key Derivation</span> — Derives a symmetric key from the shared secret.</li>
            <li><span className="text-foreground font-medium">AES-GCM Encryption</span> — Encrypts the aggregated IoT data with authenticated encryption.</li>
          </ol>
          <p>This combination provides confidentiality, integrity, and resistance to both classical and quantum attacks.</p>
        </div>
      </Section>
    </div>
  </div>
);

export default Methodology;
